### ISSUE TITLE
netifd script

### ISSUE THREAD

**Issue by bol-van** [danrl/luci-proto-wireguard#1]
The approach you have chosen to use direct "ip" command in netifd script to add routes and ips is wrong. Its hack. Look how other scripts are written. They use  proto_add_ipv4_route, proto_add_ipv4_address and so on. These function push information to netifd so it can track and manage interface. With your approach "ifstatus <ifname>" show nothing. Netifd thinks interface is down. Other openwrt components rely on netifd inteface to properly function. This is why luci does not display any info on interface, does not show ips, rx/tx bytes and so on. Because it queries netifd for the info.
Also you unconditionally add routes of allowed_ips. I guess its not always desired. If I set 0.0.0.0/0 as allowed_ips then it doesnt mean i want to have default route to wg interface. May be i want to use policy routing. You dont preserve server endpoint host dependency so default route cut from the server.

**Comment by danrl** [comment]
Thanks for the feedback. You are right, indeed this looks very "hackish". I'll try the options you mentioned. I had them in before but the script did not work well, so I went with the more hackish approach, throwing out all options I did not know the inner workings on. I think its time to add them again.

Good feedback!

**Comment by danrl** [comment]
I think it is fixed now. Thanks for the input. Very appreciated.

Feel free to re-open if you think the issue still exists.
