### ISSUE TITLE
mtu, metric, ...

### ISSUE THREAD

**Issue by bol-van** [danrl/luci-proto-wireguard#3]
Pls add standard interface settings like mtu and metic

**Comment by danrl** [comment]
Let's assume we add fields for metric and mtu under the advanced tab. Where will those values be used? In wireguard.sh or can netifd apply those directly?

**Comment by bol-van** [comment]
metric works now if "option mtu" is present in network config
mtu does not work.  it must be added to "ip link create" command

This is what I already added to my copy :

  config_get mtu "${config}" "mtu"

  # create interface
  ip link del dev "${iface}" 2>/dev/null
  local cmd="ip link add dev ${iface}"
  [ -z $mtu ] || cmd="$cmd mtu $mtu"
  cmd="$cmd type wireguard"
  ($cmd)

Code may be not perfect, just the idea.

**Comment by danrl** [comment]
Thanks.

**Comment by danrl** [comment]
Fixed with 8412f61
