### ISSUE TITLE
really?

### ISSUE THREAD

**Issue by outbackdingo** [danrl/luci-proto-wireguard#4]
Dude... sorry not to knock you but... who taught you how to make a package for WRT/LEDE ?

this is nowhere near what it should be, very few will test or adopt the software if its not properly packaged for luci and can be simply added to a build. 

see https://github.com/openwrt/luci/tree/master/applications/luci-app-shadowsocks-libev for an example

**Comment by danrl** [comment]
> Dude... sorry not to knock you but... who taught you how to make a package for WRT/LEDE ?

I am doing what? Did you even read the description of this repo?
If I stated anywhere that this is a *package* then please ignore it. It is not, it does not try to become one and it certainly makes no sense to become a package itself or an luci-app.

Are you familiar with how protocols are being integrated?

Let me explain:
- This is a beta testing repository, it is used to distribute the code in a convenient way to beta testers before it is submitted to various other repositories.
- wireguard.sh is going to the wireguard-tools repo, as discussed with its maintainer
- both proto_wireguard.lua files are going into the luci repository
- This repository should be useless once all code is upstream. In the meantime it works quite good for installing the code on latest OpenWRT snapshots and get some tests going. We don't want untested code upstream, do we?

> see https://github.com/openwrt/luci/tree/master/applications/luci-app-shadowsocks-libev for an example

I briefly looked at it, but what is it that I should learn from it?
Wireguard is an in-kernel protocol that exposes using an interface. It is not a userspace binary providing a tunX interface. How would it make sense to write an app for that? Please elaborate!

Sorry to say that, but I did not feel like your post helped improving anything here (yet). I can't see the issue right now, so I'll close it. Feel free to comment and re-open. But please provide *helpful* comments.
